---
title: "Proste rzeczy są trudne, słów kilka o tworzeniu szablonów w bookdown"
author: "Michal J. Czyz"
date: "November 8, 2018"
output:
  ioslides_presentation:
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

# Tworzenie dokumentów

## Opcje w **R**

> - R Notebook
> - (R)Markdown
> - **bookdown**
> - **blogdown**

## Dlaczego?

> - niesamowita szybkość pisania,
> - spora liczba dostępnych szablonów, 
> - wględna łatwość customizacji,
> - możliwość edycji plików nawet na smartphonie,
> - bezproblemowa współpraca z *git'em*,
> - nie trzeba wychodzić z **RStudio**.

# Alternatywy

## A czy nie lepiej w *Word'zie*? {.emphasized .build}

NIE.

---

Pliki tworzone w edytorach są nieprzenośne. Formatowanie "rozjeżdża się", przy próbie edycji pod różnymi wersjami edytora lub systemu operacyjnego.

Zagnieżdżanie obiektów (tabel, zdjęć, etc.) i dopasowywanie ich do rozmiaru strony jest zadaniem karkołomnym.

Eksport do *pdf* potrafi skutkować błędną strukturą dokumentu (przez co nie spełnia on norm WCAG 2.0).

---

Uczciwość wymaga przyznać, że w edytorach typu WYSIWYG zdecydowanie prościej tworzy się tabele o skąplikowanych formach (łączone komórki, koloryzowane, pola do wyboru).

## To może *InDesign*/*Scribus*?

*InDesign* faktycznie jest potężnym narzędziem, rownież jego cena jest potężna. Jest to genialne narzędzie do tworzenia dokumentów (np. plakatów, broszur) w których pierwszą rolę gra efekt wizualny. *Scribus* jest całkiem niezłym odpowiednikiem freeware'owym, natomiast jest toporny w obsłudze.

## Czysty *LaTeX*? *HTML*?

Zarówno *LaTeX* i *HTML* to świetne narzędzia, oferujące praktycznie nieskończone możliwości obróbki dokumentów. I w zasadzie pliki *Rmd* najczęściej będą kompilowane do tych formatów.

W przeciwieństwie do czystego *LaTeX'u* czy *HTML'a*, Markdown oferuje bardzo uproszczoną składnię, która nie odstrasza początkujących użytkowników i daje nam możliwość integracji **R** -- np. wykresów, importu tabel, obliczeń, wprost do dokumentu. 

Korzystając z gotowych formatek w zasadzie nie trzeba mieć żadnej wiedzy na temat *LaTeX'u* czy *HTML'a*, żeby stworzyć dokument w formie webowej albo *pdf*, które będą wyglądały schludnie.

# Praca z **bookdown**

## Różnice między **bookdown** a **RMarkdown**

**RMarkdown** jest rozszerzeniem składni **Markdown** -- zbioru znaczników umożliwiających szybkie i wygodne formatowanie i tworzenie tekstów.

**bookdown** jest w zasadzie *nakładką* na **RMarkdown**, umożliwiającą przede wszystkim tworzenie dokumentow/książek składających się z wielu podstron *HTML* oraz umożliwiających tworzenie odnośników do tabel, równań etc. pomiędzy tymi podstronami. Pakiet ten wspiera również prace na wielu plikach *Rmd* będących w gruncie rzeczy *rozdziałami*, oraz tworzenie wielu formatów wyjściowych na raz.

## Tworzenie szablonów

Najprościej skopiować gotowe szablony formatów, które nas interesują z katalogu pakietu i stopniowo wprowadzać do nich pożadane zmiany.

*opcja hard-core*: nie ma przeszkód w napisaniu szablonu pliku (np. *HTML* czy *tex*) od podstaw, ale wymaga to bardzo dużego nakładu pracy i odpowiednich umiejętności.

## Tricky parts | tabele

## Tricky parts | abstrakt

## Tricky parts | cytacje

# Grand Final

# Źródła

##

Prezentacja:

[https://www.github.com/mczyzj/PazuR_bookdown](https://www.github.com/mczyzj/PazuR_bookdown)

Formatki Pest Risk Assessment w bookdown:

[https://www.github.com/mczyzj/pestrPRA](https://www.github.com/mczyzj/pestrPRA)

Przykłady dokumentów z wykorzystaniem powyższych formatek:

[https://www.github.com/mczyzj/pestrPRA_examples](https://www.github.com/mczyzj/pestrPRA_examples)

Oryginalne dokumenty:

[https://bit.ly/2OxVpCA](https://bit.ly/2OxVpCA)